spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: docker
    password: 123456
    url: jdbc:mysql://111.231.228.108:3306/docker_order?characterEncoding=utf-8&useSSL=false
env: remote
person:
  name:gggg
  age:15
