spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: 111.231.228.108
server:
  port: 6061